### ISSUE TITLE
Fiji plugin does not export stack

### ISSUE THREAD

**Issue by axtimwalde** [saalfeldlab/em-thickness-estimation#16]
'Show' shows a warped stack in BDV but doies not generate a rendered stack.

**Comment by hanslovsky** [comment]
We should probably add an option to render the stack to the show dialog

relevant lines:
https://github.com/saalfeldlab/z-spacing/blob/9fd5ff37a7dcf788f5ea3bbc31459543c4e9f532/src/main/java/org/janelia/thickness/plugin/ZPositionCorrection.java#L294-L328
