### ISSUE TITLE
Fiji plugin shows warped stack in BDV but ignores calibration

### ISSUE THREAD

**Issue by axtimwalde** [saalfeldlab/em-thickness-estimation#17]
Pixel calibration in the original stack is ignored, leading to a compressed or stretched display of the warped stack in BDV when the correct z-resolution is not same as x,y-resolution.

**Comment by hanslovsky** [comment]
Stack can be scaled along z (option in dialog). We could replace this by a dialog that sets x,y,z resolution and auto-populate from calibration if present.
