### ISSUE TITLE
Manage properly with Maven

### ISSUE THREAD

**Issue by ctrueden** [saalfeldlab/em-thickness-estimation#8]
This component needs work to conform to the [Fiji contribution requirements](http://imagej.net/Fiji/Contribution_requirements):
- It needs to be deployed to the ImageJ Maven repository
- It needs to be managed by `fiji/pom-fiji`
- It needs to be declared in `fiji/fiji` as a dependency

**Comment by hanslovsky** [comment]
With the component connected to Jenkins, the first issue should be resolved. Is that correct?
- For the other two issues, should I create pull requests for `fiji/pom-fiji` and `fiji/fiji`?
- Do I need to create a non snapshot release first?
- What version of the `pom-fiji` should I have as parent? The current snapshot?
- Do I need to keep the `pom.xml` up to date with `fiji/pom-fiji`, i.e. always point to the latest version?

Thank you for your help

Philipp

**Comment by ctrueden** [comment]
Sorry for the delay in reply, @hanslovsky.

> Do I need to create a non snapshot release first?

Yes, we need to cut a `1.0.0` release before it can be managed by `pom-fiji`. And this component should not have been uploaded to Fiji before that release got cut. Fiji always ships release versions of artifacts, not snapshots, on its main update sites.

> Do I need to keep the pom.xml up to date with fiji/pom-fiji, i.e. always point to the latest version?

It is not required. But personally I would recommend doing that, so that you catch any dependency version skew early.

> What version of the pom-fiji should I have as parent? The current snapshot?

Always a release version. Ideally the latest.

> should I create pull requests for `fiji/pom-fiji` and `fiji/fiji`?

It would be great if—after you cut the `1.0.0` release using the [double push to master workflow](http://imagej.net/Development_Lifecycle#Method_3:_Double_push_to_master)—you could file a PR against `pom-fiji` that adds version management for this component accordingly. Thanks!

**Comment by hanslovsky** [comment]
Thank you for the detailed instructions, @ctrueden . I will create the PR once everything is ready.
We uploaded the original snapshot in '15 to have it out for the ISBI '15.

**Comment by hanslovsky** [comment]
Thank you for merging @ctrueden in fiji/pom-fiji#15.
